# Default values for FIAP.Diner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: cdvt/iburguer
  pullPolicy: IfNotPresent
  tag: "0.0.1"

nameOverride: ""
fullnameOverride: ""
namespace: iburguer

podLabels: {}

replicas: 1

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

resources:
  limits:
    cpu: 500m
    memory: 800Mi
  requests:
    cpu: 100m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /hc
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 5
readinessProbe:
  httpGet:
    path: /hc
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  #targetMemoryUtilizationPercentage: 80

nodeSelector: {}

configmap:
  redis:
    connectionString: "localhost:6739"
    password: 12345
  menuApi:
    url: "https://localhost:7107"