# Default values for FIAP.Diner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: matheusaoc/iburguer-shopping-cart #cdvt/iburguer-shopping-cart
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""
namespace: iburguer

podLabels: {}

replicas: 1

service:
  type: LoadBalancer
  port: 8081
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 800Mi
  requests:
    cpu: 100m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /hc
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
readinessProbe:
  httpGet:
    path: /hc
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  #targetMemoryUtilizationPercentage: 80

nodeSelector: {}

configmap:
  redis:
    connectionString: "iburguer-cache-cluster.f5keju.0001.use1.cache.amazonaws.com:6379"
    password: "p1VTSsrRWKzYp1VTSsrRWKzY"
  menu:
    url: "http://iburguer-menu:8080"
  order:
    url: "http://iburguer-ordering:8082"