apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "FIAP.Diner.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "FIAP.Diner.labels" . | nindent 4 }}
data:
  Redis__ConnectionString: {{ .Values.configmap.redis.connectionString }},password={{ .Values.configmap.redis.password }}
  Menu__Url: {{ .Values.configmap.menu.url }}
  Order__Url: {{ .Values.configmap.order.url }}
