apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "FIAP.Diner.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "FIAP.Diner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "FIAP.Diner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "FIAP.Diner.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}{{ if .Values.image.tag }}:{{ .Values.image.tag | default .Chart.AppVersion }}{{ end}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: Redis__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: {{ include "FIAP.Diner.fullname" . }}
                  key: Redis__ConnectionString
            - name: Menu__Url
              valueFrom:
                configMapKeyRef:
                  name: {{ include "FIAP.Diner.fullname" . }}
                  key: Menu__Url
            - name: Order__Url
              valueFrom:
                configMapKeyRef:
                  name: {{ include "FIAP.Diner.fullname" . }}
                  key: Order__Url
            - name: MassTransit__Region
              valueFrom:
                configMapKeyRef:
                  name: {{ include "FIAP.Diner.fullname" . }}
                  key: MassTransit__Region
            - name: MassTransit__AccessKey
              valueFrom:
                configMapKeyRef:
                  name: {{ include "FIAP.Diner.fullname" . }}
                  key: MassTransit__AccessKey
            - name: MassTransit__SecretKey
              valueFrom:
                configMapKeyRef:
                  name: {{ include "FIAP.Diner.fullname" . }}
                  key: MassTransit__SecretKey
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
